


trigger:
- main

pool:
  'default'

steps:
- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'robi-rt'
    sourceRepo: 'my-npm'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
